# Generated by Django 5.2.4 on 2026-07-18 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('target_type', models.CharField(choices=[('VIRTUAL_MACHINE', 'Virtual Machine'), ('DOCKER_CONTAINER', 'Docker Container'), ('KUBERNETES', 'Kubernetes'), ('SERVER', 'Server'), ('OTHER', 'Other')], default='SERVER', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Deployment Target',
                'verbose_name_plural': 'Deployment Targets',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Environment',
                'verbose_name_plural': 'Environments',
            },
        ),
        migrations.CreateModel(
            name='Hypervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('provider', models.CharField(choices=[('VMWARE', 'VMware'), ('HYPERV', 'Hyper-V'), ('KVM', 'KVM'), ('XEN', 'Xen'), ('PROXMOX', 'Proxmox'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('endpoint', models.URLField(blank=True)),
                ('management_port', models.PositiveIntegerField(default=443)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hypervisor',
                'verbose_name_plural': 'Hypervisors',
            },
        ),
        migrations.CreateModel(
            name='DeploymentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_tasks', to=settings.AUTH_USER_MODEL)),
                ('deployment_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_tasks', to='devops.deploymenttarget')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployment_tasks', to='projects.projetapplicatif')),
            ],
            options={
                'verbose_name': 'Deployment Task',
                'verbose_name_plural': 'Deployment Tasks',
            },
        ),
        migrations.CreateModel(
            name='DeploymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('source', models.CharField(blank=True, max_length=150)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devops.deploymenttask')),
            ],
            options={
                'verbose_name': 'Deployment Log',
                'verbose_name_plural': 'Deployment Logs',
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('artifact_type', models.CharField(blank=True, max_length=100)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('checksum', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='projects.projetapplicatif')),
                ('deployment_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='devops.deploymenttask')),
            ],
            options={
                'verbose_name': 'Artifact',
                'verbose_name_plural': 'Artifacts',
            },
        ),
        migrations.CreateModel(
            name='DockerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tag', models.CharField(default='latest', max_length=100)),
                ('repository_url', models.URLField(blank=True)),
                ('digest', models.CharField(blank=True, max_length=255)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='docker_images', to='devops.environment')),
            ],
            options={
                'verbose_name': 'Docker Image',
                'verbose_name_plural': 'Docker Images',
                'unique_together': {('name', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='deploymenttarget',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployment_targets', to='devops.environment'),
        ),
        migrations.AddField(
            model_name='deploymenttarget',
            name='hypervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_targets', to='devops.hypervisor'),
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines', to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pipelines', to='devops.environment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='projects.projetapplicatif')),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
            },
        ),
        migrations.AddField(
            model_name='deploymenttask',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='devops.pipeline'),
        ),
        migrations.CreateModel(
            name='SSHCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=22)),
                ('private_key', models.TextField(blank=True)),
                ('public_key', models.TextField(blank=True)),
                ('passphrase', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssh_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SSH Credential',
                'verbose_name_plural': 'SSH Credentials',
                'unique_together': {('name', 'host', 'port')},
            },
        ),
        migrations.AddField(
            model_name='hypervisor',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hypervisors', to='devops.sshcredential'),
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('uuid', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=150)),
                ('cpu', models.PositiveIntegerField(default=1)),
                ('memory_mb', models.PositiveIntegerField(default=1024)),
                ('disk_gb', models.PositiveIntegerField(default=20)),
                ('status', models.CharField(choices=[('STOPPED', 'Stopped'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('ERROR', 'Error')], default='STOPPED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='virtual_machines', to='devops.environment')),
                ('hypervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_machines', to='devops.hypervisor')),
                ('ssh_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_machines', to='devops.sshcredential')),
            ],
            options={
                'verbose_name': 'Virtual Machine',
                'verbose_name_plural': 'Virtual Machines',
                'unique_together': {('name', 'hypervisor')},
            },
        ),
        migrations.AddField(
            model_name='deploymenttarget',
            name='virtual_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_targets', to='devops.virtualmachine'),
        ),
        migrations.CreateModel(
            name='AnsiblePlaybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('repository_url', models.URLField(blank=True)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ansible_playbooks', to='devops.environment')),
            ],
            options={
                'verbose_name': 'Ansible Playbook',
                'verbose_name_plural': 'Ansible Playbooks',
                'unique_together': {('name', 'repository_url')},
            },
        ),
        migrations.CreateModel(
            name='EnvironmentVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150)),
                ('value', models.TextField(blank=True)),
                ('is_secret', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='devops.environment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='projects.projetapplicatif')),
            ],
            options={
                'verbose_name': 'Environment Variable',
                'verbose_name_plural': 'Environment Variables',
                'unique_together': {('key', 'environment', 'project')},
            },
        ),
        migrations.CreateModel(
            name='GitRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('provider', models.CharField(choices=[('GITHUB', 'GitHub'), ('GITLAB', 'GitLab'), ('BITBUCKET', 'Bitbucket'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='git_repositories', to='projects.projetapplicatif')),
            ],
            options={
                'verbose_name': 'Git Repository',
                'verbose_name_plural': 'Git Repositories',
                'unique_together': {('url', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('key', models.CharField(max_length=150)),
                ('value', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secrets', to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='devops.environment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='projects.projetapplicatif')),
            ],
            options={
                'verbose_name': 'Secret',
                'verbose_name_plural': 'Secrets',
                'unique_together': {('key', 'environment', 'project')},
            },
        ),
        migrations.CreateModel(
            name='TerraformWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('backend_config', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terraform_workspaces', to='devops.environment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terraform_workspaces', to='projects.projetapplicatif')),
            ],
            options={
                'verbose_name': 'Terraform Workspace',
                'verbose_name_plural': 'Terraform Workspaces',
                'unique_together': {('name', 'project')},
            },
        ),
        migrations.CreateModel(
            name='DockerContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped'), ('REMOVED', 'Removed')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='devops.dockerimage')),
                ('virtual_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docker_containers', to='devops.virtualmachine')),
            ],
            options={
                'verbose_name': 'Docker Container',
                'verbose_name_plural': 'Docker Containers',
                'unique_together': {('name', 'virtual_machine')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='deploymenttarget',
            unique_together={('name', 'environment')},
        ),
    ]
