# Generated by Django 5.2.4 on 2026-07-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150)),
                ('framework', models.CharField(blank=True, max_length=50)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('ci_platform', models.CharField(blank=True, max_length=50)),
                ('artifacts_generated', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Generation History',
                'verbose_name_plural': 'Generation Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
