# Generated by Django 5.2.4 on 2026-07-26 09:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0002_generationhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider_name', models.CharField(max_length=50)),
                ('project_data', models.JSONField()),
                ('artifacts_data', models.JSONField()),
                ('config_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('ROLLING_BACK', 'Rolling Back'), ('ROLLED_BACK', 'Rolled Back')], default='PENDING', max_length=20)),
                ('current_stage', models.CharField(blank=True, max_length=50)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Deployment Job',
                'verbose_name_plural': 'Deployment Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='devops.deploymentjob')),
            ],
            options={
                'verbose_name': 'Deployment Event',
                'verbose_name_plural': 'Deployment Events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('stage', models.CharField(blank=True, max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='devops.deploymentjob')),
            ],
            options={
                'verbose_name': 'Deployment Log Entry',
                'verbose_name_plural': 'Deployment Log Entries',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentStageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='devops.deploymentjob')),
            ],
            options={
                'verbose_name': 'Deployment Stage Progress',
                'verbose_name_plural': 'Deployment Stage Progress',
                'ordering': ['order'],
            },
        ),
    ]
