# Generated by Django 5.2.4 on 2026-06-25 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deploiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('SUCCES', 'Succès'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=15)),
                ('commit_hash', models.CharField(blank=True, max_length=40)),
                ('script_genere', models.TextField(blank=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deploiements', to='projects.projetapplicatif')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('niveau', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Avertissement'), ('ERROR', 'Erreur')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('source', models.CharField(blank=True, max_length=100)),
                ('deploiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux', to='deployments.deploiement')),
            ],
        ),
    ]
